name: Docker Image - manticoresearch

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Stop containers
      if: always()
      timeout-minutes: 60
      run: docker-compose -f "docker-compose.yml" down
